apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  labels:
    app: minio
    app.kubernetes.io/part-of: zelda-rl
type: Opaque
stringData:
  access-key: admin
  secret-key: zelda-rl-minio-2024
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
  labels:
    app: minio
    app.kubernetes.io/part-of: zelda-rl
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
    app.kubernetes.io/part-of: zelda-rl
    app.kubernetes.io/component: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
        app.kubernetes.io/part-of: zelda-rl
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command: [/bin/bash, -c]
        args:
        - minio server /data --console-address :9090
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access-key
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret-key
        - name: MINIO_REGION_NAME
          value: us-east-1
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9090
          name: console
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "2"
            memory: 4Gi
        volumeMounts:
        - name: storage
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-storage
---
apiVersion: v1
kind: Service
metadata:
  name: minio-api
  labels:
    app: minio
    app.kubernetes.io/part-of: zelda-rl
spec:
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  labels:
    app: minio
    app.kubernetes.io/part-of: zelda-rl
spec:
  selector:
    app: minio
  ports:
  - name: console
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
