# Staging: 18 envs, 6 workers, moderate resources, no GPU
apiVersion: batch/v1
kind: Job
metadata:
  name: zelda-pufferlib-training
spec:
  template:
    spec:
      tolerations: []
      containers:
      - name: pufferlib-trainer
        resources:
          requests:
            cpu: "8"
            memory: 16Gi
          limits:
            cpu: "12"
            memory: 32Gi
        env:
        - name: NUM_ENVS
          value: "18"
        - name: NUM_WORKERS
          value: "6"
        - name: EPISODE_LENGTH
          value: "30720"
        - name: EPOCH_STEPS
          value: "500000"
        - name: MINIBATCH_SIZE
          value: "4096"
        - name: S3_ENDPOINT_URL
          value: http://minio-api.zelda-rl-staging.svc.cluster.local:9000
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret-key
        - name: LLM_GATEWAY_URL
          value: http://llm-d-gateway.zelda-rl-staging.svc.cluster.local:8080
