apiVersion: batch/v1
kind: Job
metadata:
  name: zelda-evaluator
  labels:
    app: zelda-evaluator
    app.kubernetes.io/part-of: zelda-rl
    app.kubernetes.io/component: evaluator
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: zelda-evaluator
    spec:
      restartPolicy: OnFailure
      containers:
      - name: evaluator
        image: quay.io/cnuland/zelda-kuberay-worker:latest
        command: [python, scripts/run_evaluator.py]
        env:
        - name: S3_ENDPOINT_URL
          value: http://minio-api.zelda-rl.svc.cluster.local:9000
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret-key
        - name: LLM_GATEWAY_URL
          value: http://llm-d-gateway.zelda-rl.svc.cluster.local:8080
        resources:
          requests:
            cpu: "2"
            memory: 4Gi
          limits:
            cpu: "4"
            memory: 8Gi
