# Prod: 3 LLM replicas per model with full-size models
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: qwen25-vl-32b
spec:
  replicas: 3
---
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: qwen25-32b
spec:
  replicas: 3
---
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: qwen25-7b
spec:
  replicas: 3
