# Prod: 96 envs, 24 workers, full GPU
apiVersion: batch/v1
kind: Job
metadata:
  name: zelda-pufferlib-training
spec:
  template:
    spec:
      containers:
      - name: pufferlib-trainer
        resources:
          requests:
            cpu: "24"
            memory: 64Gi
            nvidia.com/gpu: "1"
          limits:
            cpu: "32"
            memory: 96Gi
            nvidia.com/gpu: "1"
        env:
        - name: NUM_ENVS
          value: "96"
        - name: NUM_WORKERS
          value: "24"
        - name: EPISODE_LENGTH
          value: "61440"
        - name: EPOCH_STEPS
          value: "2000000"
        - name: BATCH_SIZE
          value: "32768"
        - name: MINIBATCH_SIZE
          value: "8192"
        - name: S3_ENDPOINT_URL
          value: http://minio-api.zelda-rl.svc.cluster.local:9000
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret-key
        - name: LLM_GATEWAY_URL
          value: http://llm-d-gateway.zelda-rl.svc.cluster.local:8080
