apiVersion: inference.networking.x-k8s.io/v1alpha1
kind: InferencePool
metadata:
  name: qwen25-text-pool
  labels:
    app.kubernetes.io/part-of: zelda-rl
spec:
  targetPortNumber: 8080
  extensionRef:
    name: llm-d-epp-text
    group: ""
    kind: Service
  readinessGates:
  - conditionType: inference.networking.x-k8s.io/Ready
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: qwen25-7b
      llm-d.ai/role: decode
  sessionAffinityPolicy:
    type: PrefixHash
    prefixHash:
      headerName: x-session-id
      prefixLength: 16
