# Dev: 1 replica per model, smaller context for development
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: qwen25-vl-32b
spec:
  replicas: 1
---
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: qwen25-32b
spec:
  replicas: 1
---
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: qwen25-7b
spec:
  replicas: 1
