# Dev: 1 worker, 3 envs, reduced resources
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: zelda-rl
spec:
  headGroupSpec:
    template:
      spec:
        containers:
        - name: ray-head
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 8Gi
          env:
          - name: RAY_WORKERS
            value: "3"
          - name: ENVS_PER_WORKER
            value: "3"
          - name: EPISODE_LENGTH
            value: "10000"
          - name: BATCH_SIZE
            value: "1024"
          - name: S3_ENDPOINT_URL
            value: http://minio-api.zelda-rl-dev.svc.cluster.local:9000
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: access-key
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: secret-key
          - name: LLM_GATEWAY_URL
            value: http://llm-d-gateway.zelda-rl-dev.svc.cluster.local:8080
  workerGroupSpecs:
  - replicas: 1
    minReplicas: 1
    maxReplicas: 2
    groupName: pyboy-workers
    template:
      spec:
        containers:
        - name: ray-worker
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 8Gi
          env:
          - name: RAY_WORKERS
            value: "3"
          - name: ENVS_PER_WORKER
            value: "3"
          - name: EPISODE_LENGTH
            value: "10000"
          - name: BATCH_SIZE
            value: "1024"
          - name: S3_ENDPOINT_URL
            value: http://minio-api.zelda-rl-dev.svc.cluster.local:9000
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: access-key
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: secret-key
          - name: LLM_GATEWAY_URL
            value: http://llm-d-gateway.zelda-rl-dev.svc.cluster.local:8080
        nodeSelector: {}
        tolerations: []
