# Overnight run: PufferLib PPO with advancing checkpoints, 12-hour target.
# GPU-accelerated, 96 envs, 2M steps/epoch, 24 epochs, god mode throughout.
# Purpose: long-duration training with save state progression across epochs.
apiVersion: batch/v1
kind: Job
metadata:
  name: zelda-pufferlib-baseline
  labels:
    app.kubernetes.io/part-of: zelda-rl
    app.kubernetes.io/component: rl-training
    zelda-rl/phase: training
    zelda-rl/run: baseline-v1
spec:
  backoffLimit: 2
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: zelda-rl
        app.kubernetes.io/component: rl-training
        zelda-rl/run: baseline-v1
    spec:
      serviceAccountName: zelda-rl-training
      runtimeClassName: nvidia
      restartPolicy: OnFailure
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - name: pufferlib-trainer
        image: quay.io/cnuland/zelda-pufferlib-trainer:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "12"
            memory: 24Gi
            nvidia.com/gpu: "1"
          limits:
            cpu: "24"
            memory: 48Gi
            nvidia.com/gpu: "1"
        env:
        # Training loop
        - name: EPOCH
          value: "0"
        - name: MAX_EPOCHS
          value: "24"
        - name: EPOCH_STEPS
          value: "2000000"
        - name: NUM_ENVS
          value: "96"
        - name: NUM_WORKERS
          value: "12"
        - name: EPISODE_LENGTH
          value: "30000"
        - name: MINIBATCH_SIZE
          value: "2048"
        - name: USE_LSTM
          value: "false"
        # Scheduling — high entropy to maintain exploration diversity.
        # Previous values (0.003/0.0005) caused entropy collapse by epoch 2,
        # policy over-specialized on a single 3-room path.  Pokemon Red puffer
        # uses constant 0.01 — we start 50% higher and decay to 0.005.
        - name: ENTROPY_START
          value: "0.015"
        - name: ENTROPY_END
          value: "0.005"
        - name: LR_START
          value: "2.5e-4"
        - name: LR_END
          value: "1e-4"
        - name: GOD_MODE_EPOCHS
          value: "24"
        - name: STAGNATION_LIMIT
          value: "3000"
        - name: NUM_STEPS
          value: "256"
        - name: TIME_PENALTY
          value: "-0.001"
        # Exploration bonuses — must dominate coverage grind to drive room discovery
        - name: DISTANCE_BONUS
          value: "15"
        - name: DIRECTIONAL_BONUS
          value: "20"
        - name: GRID_EXPLORATION
          value: "0.02"
        # PPO core — increase updates per batch for stronger policy learning
        - name: UPDATE_EPOCHS
          value: "4"
        - name: CLIP_COEF
          value: "0.1"
        - name: GAMMA
          value: "0.998"
        # Directional target — Maku Tree area (default, advisor can override)
        - name: DIRECTIONAL_TARGET_ROW
          value: "5"
        - name: DIRECTIONAL_TARGET_COL
          value: "12"
        # Evaluation — phase-aware LLM judges + reward advisor
        - name: RUN_EVAL
          value: "true"
        - name: CLEAN_START
          value: "true"
        - name: REWARD_MODEL_PATH
          value: ""
        - name: SAVE_STATE_PATH
          value: "/home/trainer/roms/zelda.gbc.pre-maku.state"
        - name: SAVE_STATE_S3_KEY
          value: "roms/zelda.gbc.pre-maku.state"
        - name: WALKTHROUGH_PATH
          value: "data/zelda_oos_walkthrough.txt"
        # LLM judge/advisor connection — set per-route URLs for cross-namespace
        # or cross-cluster model serving.  If *_URL is set, it overrides the
        # gateway/direct pattern entirely.  Otherwise, direct mode builds URLs
        # from model name + namespace + service components.
        - name: LLM_NAMESPACE
          value: "zelda-rl"
        - name: LLM_USE_DIRECT
          value: "true"
        - name: LLM_STATE_MODEL
          value: "qwen25-7b"
        - name: LLM_PUZZLE_MODEL
          value: "qwen25-32b"
        - name: LLM_VISION_MODEL
          value: "qwen25-vl-32b"
        - name: LLM_ADVISOR_MODEL
          value: "qwen25-32b"
        # Per-route URL overrides (uncomment to point to specific endpoints):
        # - name: LLM_STATE_URL
        #   value: "http://qwen25-7b.other-ns.svc:8000/v1/chat/completions"
        # - name: LLM_PUZZLE_URL
        #   value: "http://qwen25-32b.other-ns.svc:8000/v1/chat/completions"
        # - name: LLM_VISION_URL
        #   value: "http://qwen25-vl-32b.other-ns.svc:8000/v1/chat/completions"
        # - name: LLM_ADVISOR_URL
        #   value: "http://qwen25-32b.other-ns.svc:8000/v1/chat/completions"
        # Paths
        - name: ROM_PATH
          value: "/home/trainer/roms/zelda.gbc"
        - name: PYTHONPATH
          value: "/home/trainer"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: CHECKPOINT_DIR
          value: "/tmp/pufferlib-checkpoints"
        # MinIO
        - name: S3_ENDPOINT_URL
          value: http://minio-api.zelda-rl.svc.cluster.local:9000
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret-key
