apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: zelda-rl
  labels:
    app.kubernetes.io/part-of: zelda-rl
    app.kubernetes.io/component: rl-training
    kueue.x-k8s.io/queue-name: zelda-ray-queue
spec:
  rayVersion: "2.9.0"
  enableInTreeAutoscaling: false
  headGroupSpec:
    rayStartParams: {}
    template:
      spec:
        serviceAccountName: zelda-rl-training
        tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        containers:
        - name: ray-head
          image: quay.io/cnuland/zelda-kuberay-worker:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "8"
              memory: 16Gi
            limits:
              cpu: "16"
              memory: 32Gi
          ports:
          - containerPort: 6379
            name: gcs-server
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          env:
          - name: RAY_WORKERS
            value: "10"
          - name: ENVS_PER_WORKER
            value: "1"
          - name: EPISODE_LENGTH
            value: "30000"
          - name: BATCH_SIZE
            value: "4096"
          - name: S3_ENDPOINT_URL
            value: http://minio-api.zelda-rl.svc.cluster.local:9000
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: access-key
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: secret-key
          - name: LLM_GATEWAY_URL
            value: http://openshift-ai-inference-openshift-default.openshift-ingress.svc.cluster.local
          - name: LLM_NAMESPACE
            value: zelda-rl
  workerGroupSpecs:
  - replicas: 10
    minReplicas: 3
    maxReplicas: 20
    groupName: pyboy-workers
    rayStartParams: {}
    template:
      spec:
        serviceAccountName: zelda-rl-training
        tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        containers:
        - name: ray-worker
          image: quay.io/cnuland/zelda-kuberay-worker:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "4"
              memory: 8Gi
            limits:
              cpu: "6"
              memory: 12Gi
          env:
          - name: RAY_WORKERS
            value: "10"
          - name: ENVS_PER_WORKER
            value: "1"
          - name: EPISODE_LENGTH
            value: "30000"
          - name: BATCH_SIZE
            value: "4096"
          - name: S3_ENDPOINT_URL
            value: http://minio-api.zelda-rl.svc.cluster.local:9000
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: access-key
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: secret-key
          - name: LLM_GATEWAY_URL
            value: http://openshift-ai-inference-openshift-default.openshift-ingress.svc.cluster.local
          - name: LLM_NAMESPACE
            value: zelda-rl
