apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: zelda-rl
  labels:
    app.kubernetes.io/part-of: zelda-rl
    app.kubernetes.io/component: rl-training
    kueue.x-k8s.io/queue-name: zelda-ray-queue
spec:
  rayVersion: "2.9.0"
  enableInTreeAutoscaling: false
  headGroupSpec:
    rayStartParams: {}
    template:
      spec:
        serviceAccountName: zelda-rl-training
        containers:
        - name: ray-head
          image: quay.io/cnuland/zelda-kuberay-worker:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "8"
              memory: 16Gi
            limits:
              cpu: "16"
              memory: 32Gi
          ports:
          - containerPort: 6379
            name: gcs-server
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          env:
          - name: RAY_WORKERS
            value: "30"
          - name: ENVS_PER_WORKER
            value: "6"
          - name: EPISODE_LENGTH
            value: "61440"
          - name: BATCH_SIZE
            value: "32768"
          - name: S3_ENDPOINT_URL
            value: http://minio-api.zelda-rl.svc.cluster.local:9000
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: access-key
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: secret-key
          - name: LLM_GATEWAY_URL
            value: http://llm-d-gateway.zelda-rl.svc.cluster.local:8080
  workerGroupSpecs:
  - replicas: 3
    minReplicas: 1
    maxReplicas: 10
    groupName: pyboy-workers
    rayStartParams: {}
    template:
      spec:
        serviceAccountName: zelda-rl-training
        containers:
        - name: ray-worker
          image: quay.io/cnuland/zelda-kuberay-worker:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "6"
              memory: 24Gi
            limits:
              cpu: "8"
              memory: 32Gi
          env:
          - name: RAY_WORKERS
            value: "30"
          - name: ENVS_PER_WORKER
            value: "6"
          - name: EPISODE_LENGTH
            value: "61440"
          - name: BATCH_SIZE
            value: "32768"
          - name: S3_ENDPOINT_URL
            value: http://minio-api.zelda-rl.svc.cluster.local:9000
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: access-key
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: secret-key
          - name: LLM_GATEWAY_URL
            value: http://llm-d-gateway.zelda-rl.svc.cluster.local:8080
        tolerations:
        - key: pyboy-training
          operator: Equal
          value: "true"
          effect: NoSchedule
        nodeSelector:
          node-role.kubernetes.io/pyboy-training: ""
