apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: zelda-rl-epoch-orchestrator
  labels:
    app.kubernetes.io/part-of: zelda-rl
    app.kubernetes.io/component: rl-training
    zelda-rl/phase: orchestrator
spec:
  entrypoint: python scripts/run_epoch.py
  runtimeEnvYAML: |
    pip:
      - boto3>=1.28.0
      - pyboy>=2.6.0
      - Pillow>=9.0.0
      - PyYAML>=6.0
      - httpx>=0.25.0
      - pydantic>=2.0.0
      - torch>=2.0.0
    working_dir: "."
    excludes:
      - "old/"
      - "new/"
      - "*.ipynb"
      - "*.md"
    env_vars:
      MAX_EPOCHS: "100"
      START_EPOCH: "0"
      RAY_WORKERS: "10"
      EPISODE_LENGTH: "30000"
      LLM_GATEWAY_URL: "http://openshift-ai-inference-openshift-default.openshift-ingress.svc.cluster.local"
      LLM_NAMESPACE: "zelda-rl"
  shutdownAfterJobFinishes: false
  ttlSecondsAfterFinished: 3600
  clusterSelector:
    app.kubernetes.io/part-of: zelda-rl
